version: "3.7"
services:
  robot-1:
    build:
      context: .
    ports:
      - "3001:3001"
    networks:
      - isolation-network
    environment:
      - PORT=3001
      - NAME=Robot1
      - SEED=FVLU9YOCIWBCBIHTHODAZGMFQUHYMRLMEFMOVDZOSLSTXANW9KKIFVEXGHPFAVQNER9DCBDKYQ9AZCRFS
      - PROVIDER_URL=http://energy-1:3002
  energy-1:
    build:
      context: .
    ports:
      - "3002:3002"
    networks:
      - isolation-network
    environment:
      - PORT=3002
      - NAME=EnergyWind
      - SEED=AVLU9YOCIWBCBIHTHODAZGMFQUHYMRLMEFMOVDZOSLSTXANW9KKIFVEXGHPFAVQNER9DCBDKYQ9AZCRFS
      - PROVIDER_URL=false

  robot-2:
    build:
      context: .
    ports:
      - "3003:3003"
    networks:
      - isolation-network
    environment:
      - PORT=3003
      - NAME=Robot2
      - SEED=BVLU9YOCIWBCBIHTHODAZGMFQUHYMRLMEFMOVDZOSLSTXANW9KKIFVEXGHPFAVQNER9DCBDKYQ9AZCRFS
      - PROVIDER_URL=http://energy-1:3004

  energy-2:
    build:
      context: .
    ports:
      - "3004:3004"
    networks:
      - isolation-network
    environment:
      - PORT=3004
      - NAME=EnergySolar
      - SEED=CVLU9YOCIWBCBIHTHODAZGMFQUHYMRLMEFMOVDZOSLSTXANW9KKIFVEXGHPFAVQNER9DCBDKYQ9AZCRFS
      - PROVIDER_URL=false

networks:
  isolation-network:
    driver: bridge